<?php

namespace VehiculeBundle\Repository;

/**
 * AcquisitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcquisitionRepository extends \Doctrine\ORM\EntityRepository
{
}
