<?php

namespace VehiculeBundle\Repository;

/**
 * UtilisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisationRepository extends \Doctrine\ORM\EntityRepository
{
}
